version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
jobs:
  test:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
  deploy:
    docker:
      - image: docker:stable
    
    steps:
      - run:
          name: ssh ec2 and run docker
          command: |
            ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/aws ubuntu@ec2-43-206-220-59.ap-northeast-1.compute.amazonaws.com " aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 899112647471.dkr.ecr.ap-northeast-1.amazonaws.com
            sudo docker run -d -p 3000:3000 --name nodeapp 899112647471.dkr.ecr.ap-northeast-1.amazonaws.com/circleci:lts"
workflows:
  version: 2
  build:
    jobs:
      - test:
          context: Dockerhub
      - aws-ecr/build-and-push-image:
          repo: circleci
          tag: lts
          dockerfile: Dockerfile
          path: .
          registry-id: AWS_ECR_REGISTRY_ID
          requires:
            - test
      - deploy:
          requires:
            - aws-ecr/build-and-push-image
